nQubits = 3;
signature_size = 1;
numCliffords = 1;
Bob = sender;
Alice = receiver;
seed = 2;
Bob.setSeed(seed);
Alice.setSeed(seed);
Bob.makeCliffordGates();
Alice.makeCliffordGates();
disp(Bob.clifford_gates);
disp(Alice.clifford_gates);
gates = [ Bob.clifford_gates{1}];
C = quantumCircuit(gates);
plot(C);
gates = [ Alice.clifford_gates{1}];
C = quantumCircuit(gates);
plot(C);